package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import fr.analogon.utils.Utils;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * OdhDeclarations generated by hbm2java
 */
@Entity
@Table(name = "odh_declarations")
@NoArgsConstructor	@Getter	@Setter @ToString
public class OdhDeclarations implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odde_declid", unique = true, nullable = false)
	public Integer oddeDeclid;
	@Temporal(TemporalType.DATE)
	@Column(name = "odde_datedec", length = 10)
	public Date oddeDatedec;
	@Temporal(TemporalType.DATE)
	@Column(name = "odde_datevis", length = 10)
	public Date oddeDatevis;
	@Temporal(TemporalType.DATE)
	@Column(name = "odde_datetrait", length = 10)
	public Date oddeDatetrait;
	@Column(name = "odde_bois")
	public Boolean oddeBois;
	@Column(name = "odde_bati")
	public Boolean oddeBati;
	@Column(name = "odde_nbati")
	public Boolean oddeNbati;
	@Column(name = "odde_ext")
	public Boolean oddeExt;
	@Column(name = "odde_ster")
	public Boolean oddeSter;
	@Column(name = "odde_etatpar")
	public Integer oddeEtatpar;
	@Column(name = "odde_typedecl")
	public Integer oddeTypedecl;
	@Column(name = "odde_typetrait")
	public Integer oddeTypetrait;
	@Column(name = "odde_expert")
	public Integer oddeExpert;
	//Pas besoin de convertir de boolean en string 
	//car le checkbox accepte le boolean
	/* 
	public String getOddeBois(){
		return Utils.boolToString(this.oddeBois);
	}
	public String getOddeBati(){
		return Utils.boolToString(this.oddeBati);
	}
	public String getOddeNbati(){
		return Utils.boolToString(this.oddeNbati);
	}
	public String getOddeExt(){
		return Utils.boolToString(this.oddeExt);
	}
	public String getOddeSter(){
		return Utils.boolToString(this.oddeSter);
	}
	*/
	//Convertir au type Date la date reçu au format string
	public void SetOddeDatedec(String date){
		this.oddeDatedec=Utils.stringToDate(date);
	}
	public void SetOddeDatevis(String date){
		this.oddeDatevis=Utils.stringToDate(date);
	}
	public void SetOddeDatetrait(String date){
		this.oddeDatetrait=Utils.stringToDate(date);
	}


}
