package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OdhExpprocId generated by hbm2java
 */
@Embeddable
public class OdhExpprocId implements java.io.Serializable {
	
	@Column(name = "odep_proc", nullable = false)
	private int odepProc;
	@Column(name = "elt", nullable = false)
	private int elt;

}
