package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import fr.analogon.utils.Utils;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhEtatpar generated by hbm2java
 */
@Entity
@Table(name = "odh_etatpar")
@NoArgsConstructor	@Getter	@Setter
public class OdhEtatpar implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odet_id", unique = true, nullable = false)
	private Integer odetId;
	@Column(name = "odet_type", nullable = false, length = 1)
	private char odetType='E';
	@Column(name = "odet_plomb", precision = 5)
	private Double odetPlomb;
	@Column(name = "odet_amiante", precision = 5)
	private Double odetAmiante;
	@Column(name = "odet_lot")
	private Integer odetLot;
	@Column(name = "odet_immeuble")
	private Integer odetImmeuble;
	@Column(name = "odet_termite")
	private Boolean odetTermite=false;
	@Column(name = "odet_moisissure")
	private Boolean odetMoisissure=false;;
	@Column(name = "odet_salpetre")
	private Boolean odetSalpetre=false;;
	@Column(name = "odet_humidite")
	private Boolean odetHumidite=false;
	@Column(name = "odet_commentaire", length = 250)
	private String odetCommentaire="";
	@Column(name = "odet_seuil")
	private Integer odetSeuil;

	public OdhEtatpar(Integer odetImmeuble){
		this.odetImmeuble=odetImmeuble;
	}

	//Ces getteurs permettent de convertir de boolean en string 
	//car les options de la balise select n'accepte que le string ou int
	public String getOdetTermite(){
		return Utils.boolToString(this.odetTermite);
	}
	public String getOdetMoisissure(){
		return Utils.boolToString(this.odetMoisissure);
	}
	public String getOdetSalpetre(){
		return Utils.boolToString(this.odetSalpetre);
	}
	public String getOdetHumidite(){
		return Utils.boolToString(this.odetHumidite);
	}
	

}
