package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhExpproc generated by hbm2java
 */
@Entity
@Table(name = "odh_expproc")
@NoArgsConstructor	@Getter	@Setter
public class OdhExpproc implements java.io.Serializable {
	@Embeddable
	@NoArgsConstructor	@Getter	@Setter
	public static class OdhExpprocId implements java.io.Serializable {		
		@Column(name = "odep_proc", nullable = false)
		private int odepProc;
		@Column(name = "elt", nullable = false)
		private int elt=0;
	
	}
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "odepProc", column = @Column(name = "odep_proc", nullable = false)),
			@AttributeOverride(name = "elt", column = @Column(name = "elt", nullable = false)) })
	private OdhExpprocId id=new OdhExpprocId();
	@Column(name = "odep_expert", nullable = false)
	private int odepExpert;

	public OdhExpproc(int procId,int expertId){
		this.id.setOdepProc(procId);
		this.id.setElt(expertId);
	}
}
