package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhNatures generated by hbm2java
 */
@Entity
@Table(name = "odh_natures")
@NoArgsConstructor @Getter	@Setter
public class OdhNatures implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odnt_id", unique = true, nullable = false)
	public Integer odntId;	
	@Column(name = "odnt_type", nullable = false, length = 1)
	public char odntType;	
	@Column(name = "odnt_nom", nullable = false)
	public String odntNom;	
	@Column(name = "odnt_niveau", nullable = false)
	public int odntNiveau=0;
}
