package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhNatprocId generated by hbm2java
 */
@Embeddable
@NoArgsConstructor	@Getter	@Setter
public class OdhNatprocId implements java.io.Serializable {
	@Column(name = "odnp_proc", nullable = false)
	protected int odnpProc;
	@Column(name = "elt", nullable = false)
	protected int elt;
}
