package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhNatproc generated by hbm2java
 */
@Entity
@Table(name = "odh_natproc")
@NoArgsConstructor	@Getter	@Setter
public class OdhNatproc implements java.io.Serializable {
	@Embeddable
	@NoArgsConstructor	@Getter	@Setter
	public static class OdhNatprocId implements java.io.Serializable {
		@Column(name = "odnp_proc", nullable = false)
		protected int odnpProc;
		@Column(name = "elt", nullable = false)
		protected int elt;
	}
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "odnpProc", column = @Column(name = "odnp_proc", nullable = false)),
			@AttributeOverride(name = "elt", column = @Column(name = "elt", nullable = false)) })
	private OdhNatprocId id=new OdhNatprocId();
	@Column(name = "odnp_nat", nullable = false)
	private int odnpNat=0;

	public OdhNatproc(int procId,int natId){
		this.id.setOdnpProc(procId);
		this.id.setElt(natId);
	}
}
