package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import fr.analogon.utils.Utils;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhPropslot generated by hbm2java
 */
@Entity
@Table(name = "odh_propslot")
@NoArgsConstructor	@Getter	@Setter
public class OdhPropslot implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odpl_id", unique = true, nullable = false)
	private Integer odplId;
	@Column(name = "odpl_lot", nullable = false)
	private int odplLot;
	@Column(name = "odpl_proprietaire", nullable = false)
	private int odplProprietaire;
	@Temporal(TemporalType.DATE)
	@Column(name = "odpl_datede", nullable = false, length = 10)
	private Date odplDatede;
	@Temporal(TemporalType.DATE)
	@Column(name = "odpl_datea", length = 10)
	private Date odplDatea;
	@Column(name = "odpl_nature")
	private Integer odplNature;
	@Column(name = "odpl_observations", length = 65535)
	private String odplObservations;

	//Convertir au type Date la date reçu au format string
	public void SetOdplDatede(String date){
		this.odplDatede=Utils.stringToDate(date);
	}
	public void SetOdplDatea(String date){
		this.odplDatea=Utils.stringToDate(date);
	}
}
