package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * OdhProceduresimr generated by hbm2java
 */
@Entity
@Table(name = "odh_proceduresimr")
@NoArgsConstructor @Getter @Setter	@ToString
public class OdhProceduresimr implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odimr_id", unique = true, nullable = false)
	private Integer odimrId;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odimr_date", length = 10)
	private Date odimrDate;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odimr_datefin", length = 10)
	private Date odimrDatefin;	
	@Column(name = "odimr_immeuble")
	private Integer odimrImmeuble;	
	@Column(name = "odimr_peril")
	private Integer odimrPeril;	
	@Column(name = "odimr_suiveur")
	private Integer odimrSuiveur;	
	@Column(name = "odimr_mestype", length = 1)
	private Character odimrMestype;	
	@Column(name = "odimr_commentaire", length = 100)
	private String odimrCommentaire;	
	@Column(name = "odimr_relog", nullable = false)
	private boolean odimrRelog;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datepvcar", length = 10)
	private Date odmdDatepvcar;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datesaisie", length = 10)
	private Date odmdDatesaisie;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datejug1", length = 10)
	private Date odmdDatejug1;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datejug2", length = 10)
	private Date odmdDatejug2;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datearr1", length = 10)
	private Date odmdDatearr1;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datevis1", length = 10)
	private Date odmdDatevis1;	
	@Column(name = "odmd_observ1", length = 65535)
	private String odmdObserv1;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datearr2", length = 10)
	private Date odmdDatearr2;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datevis2", length = 10)
	private Date odmdDatevis2;	
	@Column(name = "odmd_observ2", length = 65535)
	private String odmdObserv2;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datearr3", length = 10)
	private Date odmdDatearr3;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmd_datevis3", length = 10)
	private Date odmdDatevis3;	
	@Column(name = "odmd_observ3", length = 65535)
	private String odmdObserv3;	
	@Column(name = "odmp_numarrete", length = 15)
	private String odmpNumarrete;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_datearrete", length = 10)
	private Date odmpDatearrete;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_datelimrealis", length = 10)
	private Date odmpDatelimrealis;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_daterealis", length = 10)
	private Date odmpDaterealis;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_datetravnonrealis", length = 10)
	private Date odmpDatetravnonrealis;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_dateordreserv", length = 10)
	private Date odmpDateordreserv;	
	@Temporal(TemporalType.DATE)
	@Column(name = "odmp_daterealparcomm", length = 10)
	private Date odmpDaterealparcomm;	
	@Column(name = "odmp_commentaire", length = 65535)
	private String odmpCommentaire;
	
}
