package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhRelogements generated by hbm2java
 */
@Entity
@Table(name = "odh_relogements")
@NoArgsConstructor	@Getter	@Setter
public class OdhRelogements implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odre_id", unique = true, nullable = false)
	public Integer odreId;
	@Column(name = "odre_nom", nullable = false, length = 30)
	public String odreNom;
	@Column(name = "odre_type")
	public Integer odreType;
	@Column(name = "odre_adr1", nullable = false, length = 80)
	public String odreAdr1;
	@Column(name = "odre_adr2", length = 80)
	public String odreAdr2;
	@Column(name = "odre_cpost")
	public Integer odreCpost;
	@Column(name = "odre_ville", length = 30)
	public String odreVille;
	@Column(name = "odre_tel", length = 20)
	public String odreTel;
	@Column(name = "odre_fax", length = 20)
	public String odreFax;
	@Column(name = "odre_mail", length = 60)
	public String odreMail;
	@Column(name = "odre_prix", nullable = false, precision = 11)
	public BigDecimal odrePrix;
	@Column(name = "odre_gerciv", length = 4)
	public String odreGerciv;
	@Column(name = "odre_gernom", length = 30)
	public String odreGernom;
	@Column(name = "odre_gerprenom", length = 30)
	public String odreGerprenom;
	@Column(name = "odre_commentaire")
	public String odreCommentaire;

}
