package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhSyndics generated by hbm2java
 */
@Entity
@Table(name = "odh_syndics")
@NoArgsConstructor @Getter @Setter
public class OdhSyndics implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odsyn_id", unique = true, nullable = false)
	private Integer odsynId;
	@Column(name = "odsyn_code", nullable = false, length = 3)
	private String odsynCode;	
	@Column(name = "odsyn_raison", nullable = false, length = 60)
	private String odsynRaison;	
	@Column(name = "odsyn_adr1", nullable = false, length = 80)
	private String odsynAdr1;	
	@Column(name = "odsyn_adr2", length = 80)
	private String odsynAdr2;	
	@Column(name = "odsyn_cpost")
	private Integer odsynCpost;	
	@Column(name = "odsyn_ville", length = 60)
	private String odsynVille;	
	@Column(name = "odsyn_com", length = 80)
	private String odsynCom;	
	@Column(name = "odsyn_telfix", length = 20)
	private String odsynTelfix;	
	@Column(name = "odsyn_fax", length = 20)
	private String odsynFax;	
	@Column(name = "odsyn_mail", length = 60)
	private String odsynMail;	
	@Column(name = "odsyn_rcivil", length = 4)
	private String odsynRcivil;	
	@Column(name = "odsyn_rpren", nullable = false, length = 30)
	private String odsynRpren;	
	@Column(name = "odsyn_rnom", nullable = false, length = 30)
	private String odsynRnom;	
	@Column(name = "odsyn_rtelfix", length = 20)
	private String odsynRtelfix;	
	@Column(name = "odsyn_rtelport", length = 20)
	private String odsynRtelport;	
	@Column(name = "odsyn_rmail", length = 60)
	private String odsynRmail;
	
}

