package fr.analogon.entities;

// Generated 6 oct. 2022 18:44:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * OdhSuiveurs generated by hbm2java
 */
@Entity
@Table(name = "odh_suiveurs")
@NoArgsConstructor @Getter @Setter
public class OdhSuiveurs implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "odsu_id", unique = true, nullable = false)
	private Integer odsuId;
	@Column(name = "odsu_civil", length = 4)
	private String odsuCivil;
	@Column(name = "odsu_pren", nullable = false, length = 30)
	private String odsuPren;
	@Column(name = "odsu_nom", nullable = false, length = 30)
	private String odsuNom;
	@Column(name = "odsu_adr1", nullable = false, length = 80)
	private String odsuAdr1;
	@Column(name = "odsu_adr2", length = 80)
	private String odsuAdr2;
	@Column(name = "odsu_cpost")
	private Integer odsuCpost;
	@Column(name = "odsu_ville", length = 60)
	private String odsuVille;
	@Column(name = "odsu_libelle", length = 80)
	private String odsuLibelle;
	@Column(name = "odsu_telfix", length = 20)
	private String odsuTelfix;
	@Column(name = "odsu_telport", length = 20)
	private String odsuTelport;
	@Column(name = "odsu_mail", length = 20)
	private String odsuMail;

}
